server:
  port: 9090

spring:
  main:
    allow-circular-references: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/YemekSepetiDB"
    username: "postgres"
    password: "192837"
    driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
